apiVersion: v1
kind: PersistentVolume
metadata:
  name: blackbox-exporter-pv
  namespace: blackbox-exporter
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /exports/blackbox-exporter
    server: 10.7.0.69

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackbox-exporter-pvc
  namespace: blackbox-exporter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: blackbox-exporter-pv
