apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 300s  # How often Prometheus scrapes targets, you can change this value according to your needs.

    scrape_configs:
      - job_name: 'node-exporter'
        metrics_path: /metrics
        static_configs:
          - targets:
              - "10.7.0.79:9100"
              - "10.7.0.76:9100"
              - "10.7.0.75:9100"
              - "10.7.0.69:9100"
              - "10.7.0.74:9100"
              - "10.7.0.78:9100"