apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 300s  # How often Prometheus scrapes targets, you can change this value according to your needs.

    scrape_configs:
      - job_name: 'node-exporter'
        metrics_path: /metrics
        static_configs:
          - targets:
              - "10.7.0.79:9100"
              - "10.7.0.76:9100"
              - "10.7.0.75:9100"
              - "10.7.0.69:9100"
              - "10.7.0.74:9100"
              - "10.7.0.78:9100"
    
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]  # Look at the Blackbox Exporter documentation to see other modules
        static_configs:
          - targets:
            - http://jenkins.homelab.local
            - http://grafana.homelab.local
            - http://prometheus.homelab.local
            - http://pihole.homelab.local/admin
            - http://homepage.homelab.local
            - http://kibana.homelab.local
            - http://portainer.homelab.local
            - http://traefik.homelab.local
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter.blackbox-exporter.svc.cluster.local:9115
            