apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-prometheus
  namespace: prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /exports/prometheus
    server: 10.7.0.69
