apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/kubedata/prometheus
    server: 10.7.0.71  # Change this to your NFS server address
