apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.7.0.69
    path: /exports/traefik