apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-nfs-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: traefik-nfs-pv