# values.yaml for Traefik
image:
  name: traefik
  tag: "2.6"

service:
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local

additionalArguments:
  - "--log.level=INFO"
  - "--api.dashboard=true"

ingressRoute:
  dashboard:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik

ports:
  web:
    redirectTo: websecure

  websecure:
    tls:
      enabled: true
      options: default
      certResolver: myresolver

certificatesResolvers:
  myresolver:
    acme:
      email: nick.turner82@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
