apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-grafana
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/kubedata/grafana
    server: 10.7.0.71  # Change this to your NFS server address
