apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/18visions
  services.yaml: |
    - My First Group:
        - Pi-hole:
            href: http://pihole.homelab.local
            description: Pi-hole
            icon: pi-hole
        - ArgoCD:
            href: http://argocd.homelab.local
            description: ArgoCD
            icon: argocd
        - Proxmox:
            href: https://proxmox.homelab.local
            description: Proxmox
            icon: proxmox
            
    - My Second Group:
        - Jenkins:
            href: http://jenkins.homelab.local
            description: Jenkins CI/CD
            icon: jenkins
        - RabbitMQ:
            href: http://rabbitmq.homelab.local
            description: RabbitMQ
            icon: rabbitmq
        - Home Assistant:
            href: http://homeassistant.local:8123
            description: Home Assistant
            icon: homeassistant

    - My Third Group:
        - Grafana:
            href: http://grafana.homelab.local
            description: Grafana
            icon: grafana
        - Prometheus:
            href: http://prometheus.homelab.local
            description: Prometheus
            icon: prometheus
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""