apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`homepage.homelab.local`)
    kind: Rule
    services:
    - name: homepage
      port: 80
  tls:
    certResolver: myresolver