apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-homepage
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/kubedata/homepage
    server: 10.7.0.71
