apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
spec:
  type: NodePort
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
      nodePort: 31200
      name: http
  selector:
    app.kubernetes.io/name: homepage