apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-rabbitmq
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/kubedata/rabbitmq
    server: 10.7.0.71
