apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 15672
    targetPort: 15672
    protocol: TCP
    nodePort: 30672  # Optionally specify a node port or allow Kubernetes to assign one
  - name: amqp
    port: 5672
    targetPort: 5672
    protocol: TCP
    nodePort: 30676  # Optionally specify a node port or allow Kubernetes to assign one
  selector:
    app: rabbitmq
