apiVersion: v1
kind: PersistentVolume
metadata:
  name: homarr-pv
  namespace: homarr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /exports/homarr
    server: 10.7.0.69

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-pvc
  namespace: homarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: homarr-pv
  storageClassName: nfs