apiVersion: v1
kind: PersistentVolume
metadata:
  name: homarr-config-pv
  namespace: homarr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /exports/homarr
    server: 10.7.0.69

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-config-pvc
  namespace: homarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: homarr-config-pv
  storageClassName: nfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homarr-data-pv
  namespace: homarr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /exports/homarr
    server: 10.7.0.69

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-data-pvc
  namespace: homarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: homarr-data-pv
  storageClassName: nfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homarr-icons-pv
  namespace: homarr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /exports/homarr
    server: 10.7.0.69

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-icons-pvc
  namespace: homarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: homarr-icons-pv
  storageClassName: nfs
