apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
          - port: 8080  # for web UI
            targetPort: 8080
            protocol: TCP
            name: http
          - port: 50000  # for JNLP agents
            targetPort: 50000
            protocol: TCP
            name: jnlp
        volumeMounts:
        - name: jenkins-storage
          mountPath: /var/jenkins_home
        env:
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false"
      volumes:
      - name: jenkins-storage
        persistentVolumeClaim:
          claimName: jenkins-pvc
