apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    nodePort: 32050
    protocol: TCP
  - name: agents
    port: 8090
    targetPort: 8090
    nodePort: 32051
    protocol: TCP
  selector:
    app: jenkins
