apiVersion: v1
kind: Service
metadata:
  name: awx-web-svc
  namespace: awx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8052
      nodePort: 30120  # Optional: Specify a fixed node port if required
  selector:
    app.kubernetes.io/instance: awx
    app.kubernetes.io/name: awx-web
