apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ansible/awx-operator/config/default?ref=2.15.0
  - pv.yaml
  - pvc.yaml
  - awx-cr.yaml
  - awx-service.yaml

namespace: awx

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.15.0
