apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-awx
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/kubedata/awx
    server: 10.7.0.71
