apiVersion: v1
kind: Service
metadata:
  name: awx-service
spec:
  type: NodePort
  ports:
  - port: 8052
    targetPort: 8052
    protocol: TCP
    nodePort: 32052  # Optionally specify a node port or let Kubernetes choose one
  selector:
    app: awx
