apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/kubedata/logstash
    server: 10.7.0.71