name: Kubernetes Deployment

on:
  push:
    paths:
      - "prometheus/**"
    branches:
      - master

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Namespace
        run: |
          kubectl create namespace prometheus || true

      - name: Deploy App(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f prometheus/deployment.yaml --validate=false

      - name: Deploy App(Service)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f prometheus/service.yaml --validate=false

      - name: Deploy App(PV)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f prometheus/pv.yaml --validate=false

      - name: Deploy App(PVC)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f prometheus/pvc.yaml --validate=false